# mode = "server"

## uses default values if not present
# [trojan]
# password = [] # optional
## uses built-in if not present
# fallback = "baidu.com:80" # optional

[tls]
# listen = "0.0.0.0:443" # optional
# tcp_nodelay = false # optional
sni = "example.com" # required
cert = "fullchain.pem" # required
key = "privkey.pem" # required

## doesn't use redis if not present
# [redis]
# server = "localhost:5678" # optional